//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityExample
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DbStudentEntities : DbContext
    {
        public DbStudentEntities()
            : base("name=DbStudentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_class> tbl_class { get; set; }
        public virtual DbSet<tbl_grade> tbl_grade { get; set; }
        public virtual DbSet<tbl_student> tbl_student { get; set; }
        public virtual DbSet<tbl_clubs> tbl_clubs { get; set; }
    
        public virtual ObjectResult<GradeList_Result> GradeList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GradeList_Result>("GradeList");
        }
    }
}
