//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityExample
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_grade
    {
        public int GradeID { get; set; }
        public Nullable<int> Student { get; set; }
        public Nullable<int> Class { get; set; }
        public Nullable<short> Exam1 { get; set; }
        public Nullable<short> Exam2 { get; set; }
        public Nullable<short> Exam3 { get; set; }
        public Nullable<decimal> Average { get; set; }
        public Nullable<bool> Situation { get; set; }
    
        public virtual tbl_class tbl_class { get; set; }
        public virtual tbl_student tbl_student { get; set; }
    }
}
